---
apiVersion: v1
kind: Service
metadata:
  name: animals-api
spec:
  type: NodePort
  selector:
    app: animals-api
  ports:
  - port: 8080
    name: http
---
apiVersion: v1
kind: Service 
metadata:     
  name: animals-api-istio
spec:
  type: NodePort
  ports:
  - name: istio-proxy
    port: 15020
    protocol: TCP
