---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: animals-api-istio
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: animals-api
  endpoints:
  - interval: 30s
    path: /stats/prometheus
    port: istio-proxy
